#!/usr/bin/env python3
"""品牌标志几何的唯一出处：生成 assets/brand/*.svg、assets/icon/icon.svg，
并同步 web/index.html 的 favicon。

标志「一页正在排版的 Figure」分三档（不是等比缩放，是三个形）：
    full     ≥ 40 px   五元素齐全，两级线宽 20 / 10
    compact  22–39 px  去分栏线，结构线加粗到 32
    mini     ≤ 21 px   反转为实心 Ink 底，只剩色块
几何与配色规则来自 Magplot Brand System Rev 2.0。改动几何只改本文件，
然后重跑：

    python scripts/build_brand_assets.py      # 再跑 build_icons.py 重出 .icns/.ico

界面内的标志由 web/src/components/ui/BrandMark.tsx 用同一张几何表绘制
（色值走 CSS token）；README hero（assets/readme/hero.svg）内嵌一份 full 版。
这两处的坐标以本文件为准，改几何时须同步。
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

for _s in (sys.stdout, sys.stderr):
    if hasattr(_s, "reconfigure"):
        _s.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
BRAND_DIR = ROOT / "assets" / "brand"
ICON_SVG = ROOT / "assets" / "icon" / "icon.svg"
INDEX_HTML = ROOT / "web" / "index.html"

# ---------------------------------------------------------------------------
# 几何（viewBox 0 0 1024 1024，坐标全部为 2 的倍数）。
# 角色：base=mini 的实心底；grey=已排好的面板；ink=框与分栏线；blue=正在处理的块。
# ---------------------------------------------------------------------------
GEOMETRY: dict[str, list[tuple[str, dict[str, int]]]] = {
    "full": [
        ("grey", dict(x=98, y=98, w=492, h=340)),
        ("grey", dict(x=652, y=652, w=284, h=284)),
        ("ink-stroke", dict(x=88, y=88, w=848, h=848, sw=20)),
        ("ink-stroke", dict(x=652, y=652, w=284, h=284, sw=20)),
        ("ink", dict(x=88, y=433, w=848, h=10)),
        ("blue", dict(x=596, y=596, w=112, h=112)),
    ],
    "compact": [
        ("grey", dict(x=110, y=110, w=480, h=328)),
        ("grey", dict(x=656, y=656, w=272, h=272)),
        ("ink-stroke", dict(x=96, y=96, w=832, h=832, sw=32)),
        ("ink-stroke", dict(x=656, y=656, w=272, h=272, sw=32)),
        ("blue", dict(x=592, y=592, w=128, h=128)),
    ],
    "mini": [
        ("base", dict(x=0, y=0, w=1024, h=1024)),
        ("grey", dict(x=96, y=96, w=528, h=368)),
        ("grey", dict(x=592, y=592, w=336, h=336)),
        ("blue", dict(x=512, y=512, w=160, h=160)),
    ],
}

# 配色（独立 SVG 里色值固定是可移植资产的正常需求；界面内走 CSS token）：
#   surface  白底 / surface：灰 #e3e3dd
#   paper    纸色 #f2f2ef / 画布底：灰换 #cfcfc7
#   reverse  深底：整体换 #f2f2ef，灰 #5c5c55，蓝提亮 #4a8ede（仅此场合）
#   mono     单色黑（印刷）：蓝并入黑，灰 #d8d8d0
PALETTES: dict[str, dict[str, str]] = {
    "surface": {"base": "#1b1b18", "grey": "#e3e3dd", "ink": "#1b1b18", "blue": "#2868b7"},
    "paper": {"base": "#1b1b18", "grey": "#cfcfc7", "ink": "#1b1b18", "blue": "#2868b7"},
    "reverse": {"base": "#f2f2ef", "grey": "#5c5c55", "ink": "#f2f2ef", "blue": "#4a8ede"},
    "mono": {"base": "#000000", "grey": "#d8d8d0", "ink": "#000000", "blue": "#000000"},
}

GENERATED = "GENERATED by scripts/build_brand_assets.py — do not edit by hand"


def rects(variant: str, palette: dict[str, str], indent: str = "  ") -> str:
    out = []
    for role, g in GEOMETRY[variant]:
        if role == "ink-stroke":
            out.append(
                f'{indent}<rect x="{g["x"]}" y="{g["y"]}" width="{g["w"]}" height="{g["h"]}"'
                f' fill="none" stroke="{palette["ink"]}" stroke-width="{g["sw"]}"/>'
            )
        else:
            out.append(
                f'{indent}<rect x="{g["x"]}" y="{g["y"]}" width="{g["w"]}" height="{g["h"]}"'
                f' fill="{palette[role]}"/>'
            )
    return "\n".join(out)


def mark_svg(variant: str, palette_name: str) -> str:
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"\n'
        f'     role="img" aria-label="Magplot">\n'
        f"  <!-- {GENERATED} · {variant} / {palette_name} -->\n"
        f"{rects(variant, PALETTES[palette_name])}\n"
        f"</svg>\n"
    )


def icon_svg() -> str:
    """桌面应用图标：full 版放进现有 squircle 容器（rx 228/1024、#f2f2ef 底）。

    容器属于平台，不属于标志本体。底是纸色，灰块随背景换 #cfcfc7。
    标志缩放 0.8125 居中：外框落在 168–857，四边留白 ≈ 1/4 × 边长，
    视觉占位与旧图标的纸张（x=168, w=688）一致。
    """
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024"\n'
        '     viewBox="0 0 1024 1024" role="img" aria-label="Magplot">\n'
        f"  <!-- {GENERATED} -->\n"
        "  <defs>\n"
        '    <clipPath id="squircle">\n'
        '      <rect width="1024" height="1024" rx="228"/>\n'
        "    </clipPath>\n"
        "  </defs>\n"
        '  <g clip-path="url(#squircle)">\n'
        '    <rect width="1024" height="1024" fill="#f2f2ef"/>\n'
        '    <g transform="translate(96 96) scale(0.8125)">\n'
        f'{rects("full", PALETTES["paper"], indent="      ")}\n'
        "    </g>\n"
        "  </g>\n"
        "</svg>\n"
    )


def favicon_href() -> str:
    """favicon：mini 版内联 data URI，无圆角容器、无透明度。

    16 px 下矩形边缘落在半像素上，crispEdges 让纯色块吸附到像素网格。
    """
    body = rects("mini", PALETTES["surface"], indent="").replace("\n", "")
    svg = (
        "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1024 1024'"
        " shape-rendering='crispEdges'>" + body.replace('"', "'") + "</svg>"
    )
    return "data:image/svg+xml," + svg.replace("#", "%23").replace("<", "%3C").replace(">", "%3E")


def main() -> int:
    BRAND_DIR.mkdir(parents=True, exist_ok=True)
    files = {
        "magplot-mark.svg": mark_svg("full", "surface"),
        "magplot-mark-compact.svg": mark_svg("compact", "surface"),
        "magplot-mark-mini.svg": mark_svg("mini", "surface"),
        "magplot-mark-paper.svg": mark_svg("full", "paper"),
        "magplot-mark-reverse.svg": mark_svg("full", "reverse"),
        "magplot-mark-mono.svg": mark_svg("full", "mono"),
    }
    for name, text in files.items():
        (BRAND_DIR / name).write_text(text, encoding="utf-8")
        print(f"✓ assets/brand/{name}")

    ICON_SVG.write_text(icon_svg(), encoding="utf-8")
    print("✓ assets/icon/icon.svg")

    html = INDEX_HTML.read_text(encoding="utf-8")
    new_html, n = re.subn(
        r'(<link rel="icon" href=")[^"]*(" />)',
        lambda m: m.group(1) + favicon_href() + m.group(2),
        html,
    )
    if n != 1:
        print(f"web/index.html 里找到 {n} 处 favicon（预期 1），未写入", file=sys.stderr)
        return 1
    if new_html != html:
        INDEX_HTML.write_text(new_html, encoding="utf-8")
        print("✓ web/index.html favicon")
    else:
        print("· web/index.html favicon 已是最新")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
